### ISSUE TITLE
LocationInfo - window.google not defined 

### ISSUE THREAD

**Issue by inseokr** [inseokr/MERN_linkedspace#169]
How to reproduce?

1. create a landlord listing
2. add it as a child listing to a tenant dashboard
3. click a child listing associated with the landlord listing
<note> The external URL will be something like this.
http://10.0.0.77:5000/listing/landlord/5f542b25ad7cd485c08f94a7/get

Page doesn't render due to a problem around window.google.

**Comment by justin-seo** [comment]
https://github.com/inseokr/MERN_linkedspace/pull/178
