### ISSUE TITLE
Marker doesn't have relevant image.

### ISSUE THREAD

**Issue by inseokr** [inseokr/MERN_linkedspace#192]
It's supposed to show the cover image or profile picture of listing creator.
Currently it shows the same default image always.

**Comment by inseokr** [comment]
![image](https://user-images.githubusercontent.com/4754808/94512348-ae0f5d80-01d0-11eb-8b95-f2ec888b41d3.png)

**Comment by inseokr** [comment]
It looks like the image is default. 

<note> I see correct image inside listing page though. The problem is shown in:

- tenant dashboard

- /Map page

**Comment by justin-seo** [comment]
https://github.com/inseokr/MERN_linkedspace/tree/issue-192-always-default-marker
