### ISSUE TITLE
Price filter - zIndex value should be adjusted

### ISSUE THREAD

**Issue by inseokr** [inseokr/MERN_linkedspace#345]
![image](https://user-images.githubusercontent.com/4754808/103250574-67451700-4929-11eb-9f1e-69cbdcdfeb85.png)

**Comment by inseokr** [comment]
zIndex of parent listing is set to 255 which is pretty high.
You may set a bigger value than parent listing to make it on top.

**Comment by justin-seo** [comment]
fixed by changing z value
