### ISSUE TITLE
contexts/ListingContext undefined googleMapRef ({current: undefined})

### ISSUE THREAD

**Issue by justin-seo** [inseokr/MERN_linkedspace#35]
When you initialize googleMapRef from the Map.jsx it returns an object containing the map div ({current: div}). But when you move that to the ListingContext context, the initialized googleMapRef is undefined. May have to do with lifecycle of contexts.

To reproduce, just enter anything into the City, State, Country search field to go to the Map page. In the DevTool, look at the console to see both initialized googleMapRef. googleMapRef will be undefined in the context and have the proper attributes in Map.jsx.

**Comment by inseokr** [comment]
![map error](https://user-images.githubusercontent.com/4754808/82742774-0ad8a400-9d17-11ea-8d18-0edba190e5ca.png)

I'mdon't see the problem you described.

**Comment by inseokr** [comment]
Please close it if this issue's something already addressed.

**Comment by inseokr** [comment]
It's already fixed.
