### ISSUE TITLE
Landlord listing - No embedded map

### ISSUE THREAD

**Issue by inseokr** [inseokr/MERN_linkedspace#500]

**Comment by inseokr** [comment]
@justin-seo , this is one of priority issue on your plate. Please get to this first if you come to have any bandwidth.

**Comment by justin-seo** [comment]
OK will prioritize this one On Feb 18, 2021 10:50 PM, inseokr <notifications@github.com> wrote:
@justin-seo , this is one of priority issue on your plate. Please get to this first if you come to have any bandwidth.
