### ISSUE TITLE
No map is available in the deployed service

### ISSUE THREAD

**Issue by inseokr** [inseokr/MERN_linkedspace#524]
I could see map in the case of local service, not in the deployed service.

**Comment by inseokr** [comment]
This issue is not reproducible 100%. It's happening randomly.

**Comment by inseokr** [comment]
I don't see any API call. It's not reliable.

We may consider switching back to google embedded map if we can't solve this problem.

**Comment by justin-seo** [comment]
seems to behave better after fix. can reopen if issue persists.
