### ISSUE TITLE
Not able to change tome frame when creating a NEW EVENT on the APP

### ISSUE THREAD

**Issue by ybsthecliq** [inseokr/MERN_linkedspace#701]
![image](https://user-images.githubusercontent.com/71202433/122627787-afd2c700-d066-11eb-8732-5e3dbd2487d9.png)

**Comment by ybsthecliq** [comment]
Stuck at 7 pm

**Comment by inseokr** [comment]
Unfortunately I can't reproduce it. Can you try it again??
