### ISSUE TITLE
The event date sets a day forward automatically

### ISSUE THREAD

**Issue by ybsthecliq** [inseokr/MERN_linkedspace#707]
In the video you will see me setting the event date as the 25th of June, after creating it the date is set as the 26th and not the 25th
https://user-images.githubusercontent.com/71202433/122862662-553fa200-d2d6-11eb-9331-1075eea4dd50.MOV

**Comment by inseokr** [comment]
Hmm... I watched your video, but I couldn't reproduce the issue from my phone. 

https://user-images.githubusercontent.com/4754808/122866024-27f5f280-d2dc-11eb-9211-a31825a071df.mp4
